name: ITD Skuid Pages Deployment
description: GitHub Action Script to Deploy the Skuid Pages to a given environment
author: csilva-intakedesk
branding:
  icon: terminal
  color: red

inputs:
  LOG_LEVEL:
    description: >
      Skuid command flag --loglevel. Logging level for this command invocation.
      Defaults to Error.
    type: choice
    default: error
    options:
      - trace
      - debug
      - info
      - warn
      - error
      - fatal
  TARGET_USERNAME_ALIAS:
    description: >
      Skuid command flag --targetusername. Username or alias for the target org;
      overrides default target org set with SF.
    type: string
  MODULES:
    description: >
      The Skuid command flag --modules. It will default to ITD modules. Should
      be passed separated by comma if more than one.
    type: string
  SF_AUTH_URL:
    description: The Salesforce Auth URL
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Install Salesforce CLI
      shell: bash
      run: |
        npm install -g @salesforce/cli
        sf version --verbose --json

    - name: Installing SF Skuid Pages Plugin
      shell: bash
      run: |
        echo y | sf plugins install skuid-sfdx
        sf plugins

    - name: Environment Login
      shell: bash
      run: |
        sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ inputs.SF_AUTH_URL }}")

    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45.0.1

    - name: List Files for Debugging
      run: ls -R /home/runner/work/itd-sf/itd-sf

    - name: SKUID Pages Deployment
      shell: bash
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        TARGET_USERNAME_ALIAS: ${{ inputs.TARGET_USERNAME_ALIAS }}
        GH_TOKEN: ${{ github.token }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        python3 deploy_skuid_pages.py
